const Config = {
    PUB_KEY: "-----BEGIN PUBLIC KEY-----MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQB0cAUXx1O0EySTUcWdXUl0rO/HmKxM5DcmtRwuD9bVYsVYNT4bancz8W604CkNHnDP1RMLPPfpWvFqvF46tUc6813BvcOwQAEANILBu1zKFyGR/GOGkvVTONxznoLbIHMwBPtriKGWba2FHX0Ss/c7aVJ3jsE9ZNnY8DLJr25XQc9lhfjkWh9eUnGjE8PfDrk1cbDD4L7XvlPjwAkQn4P70haaNeuWHSAaySb6ZMNeFzvLfbk6p9zid/c5PDJZ4TRFhuYdNOPvexF6k470M3pIsWJo/fru+3ehOTfHVbM8GTZewVCP7T0rdY/8njJgdaHngG0kkq4/5JALOOkk5m3NAgMBAAE=-----END PUBLIC KEY-----",
    CLIENT_ID : process.env.REACT_APP_CLIENT_ID,
    CLIENT_SECRET : process.env.REACT_APP_CLIENT_SECRET,
    CLIENT_TAG : process.env.REACT_APP_CLIENT_TAG,
    APPLICATION_CODE : process.env.REACT_APP_APPLICATION_CODE,
    API_LOGIN : process.env.REACT_APP_API_LOGIN,
    API_SERVICE: process.env.REACT_APP_API_SERVICE
}

export default Config;
