export const COLLPSE_CHANGE = 'COLLPSE_CHANGE'
export const COLLPSE_OPEN_DRAWER = 'COLLPSE_OPEN_DRAWER'
export const TOGGLE_ALL = 'TOGGLE_ALL'
export const CHANGE_OPEN_KEYS = 'CHANGE_OPEN_KEYS'
export const CHANGE_CURRENT = 'CHANGE_CURRENT'
export const CLEAR_MENU = 'CLEAR_MENU'

//Login
export const LOGIN_SET_LOADER = 'LOGIN_SET_LOADER'
export const LOGIN_HANDLE_STATE = 'LOGIN_HANDLE_STATE'
export const LOGIN_POST_DATA = 'LOGIN_POST_DATA'
export const LOGIN_SET_DATA = 'LOGIN_SET_DATA'
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT'

export const DASHBOARD_HANDLE_STATE = 'DASHBOARD_HANDLE_STATE'
export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const DELETE_TODO = 'DELETE_TODO'

export const BACK_LOGIN = 'BACK_LOGIN'

//Master
export const MASTER_HANDLE_STATE = 'MASTER_HANDLE_STATE'
export const MASTER_SET_JENKEL = 'MASTER_SET_JENKEL'

// Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

// Home
export const INIT_DATA_HOME = "INIT_DATA_HOME"
export const INIT_DATA_HOME_SUCCESS = "INIT_DATA_HOME_SUCCESS"
export const HANDLE_CHANGE_HOME = 'HANDLE_CHANGE_HOME'
export const GET_DATA_HOME = "GET_DATA_HOME"
export const DATA_CART_HOME = "DATA_CART_HOME"
export const FILTER_DATA_PRODUCT = "FILTER_DATA_PRODUCT"
export const FAV_DATA_HOME = "FAV_DATA_HOME"
